### ISSUE TITLE
Send Poll: Reply Markup is Optional, but needs unfold()

### ISSUE THREAD

**Issue by Libric0** [cmd410/OrigamiBot#28]
Hi!

Thank you for making this great project. I got a bot up and running in Minutes!

I think I discovered a little bug: In the send_poll method, you marked `reply_markup` as optional. 
However, in the [implementation](https://github.com/cmd410/OrigamiBot/blob/707eee992fa8424dbeed80d1df1a4c6629fe537d/origamibot/core/api_request.py), you call `reply_markup.unfold()` without checking whether it is None, leading to the following exception:
```
File "/home/user/.local/lib/python3.10/site-packages/origamibot/core/api_request.py", line 736, in send_poll
    'reply_markup': reply_markup.unfold(),
AttributeError: 'NoneType' object has no attribute 'unfold'
```

**Comment by cmd410** [comment]
Yeah, thats bad. Truthfully never used reply_markup except in send_message, thats how the bug got through. I see a couple more places where this is a problem. Will look into it in a couple of days. Thanks for your bug report👍
